-- Create SHOPPING_CART
CREATE TABLE `SHOPPING_CART` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_IDENTIFIER` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CUST_IDENTIFIER_UNIQUE` (`CUSTOMER_IDENTIFIER`)
) ENGINE=InnoDB AUTO_INCREMENT=128 DEFAULT CHARSET=utf8;


-- Create CART_LINE_ITEM
CREATE TABLE `CART_LINE_ITEM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CART_ID` int(11) NOT NULL,
  `PRODUCT_CODE` varchar(30) NOT NULL,
  `QUANTITY` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CART_PROD_UNIQUE` (`CART_ID`,`PRODUCT_CODE`),
  KEY `CART_FK_idx` (`CART_ID`),
  CONSTRAINT `ITEM_CART_FK` FOREIGN KEY (`CART_ID`) REFERENCES `SHOPPING_CART` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=106 DEFAULT CHARSET=utf8;
